[python]
symbol = " "
style = "bold green"

[battery]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
# error_symbol = "[✖](bold red) "


