import = ["~/.config/alacritty/themes/themes/ayu_dark.toml"]

[colors.primary]
background = "#000000"
foreground = "#edecee"

[colors.cursor]
text = '#0E1415'
cursor = '#ECEFF4'

[window]
padding.x = 10
padding.y = 10

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetbrainsMono Nerd Font"

size = 10.5
